# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import can_bridge_pb2 as proto_dot_can__bridge__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/can_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CanBridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/canbridge.v1.CanBridge/Ping',
                request_serializer=proto_dot_can__bridge__pb2.PingReq.SerializeToString,
                response_deserializer=proto_dot_can__bridge__pb2.PingResp.FromString,
                _registered_method=True)
        self.ListIfaces = channel.unary_unary(
                '/canbridge.v1.CanBridge/ListIfaces',
                request_serializer=proto_dot_can__bridge__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_can__bridge__pb2.IfacesResp.FromString,
                _registered_method=True)
        self.SendFrame = channel.unary_unary(
                '/canbridge.v1.CanBridge/SendFrame',
                request_serializer=proto_dot_can__bridge__pb2.SendFrameReq.SerializeToString,
                response_deserializer=proto_dot_can__bridge__pb2.SendAck.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/canbridge.v1.CanBridge/Subscribe',
                request_serializer=proto_dot_can__bridge__pb2.SubscribeReq.SerializeToString,
                response_deserializer=proto_dot_can__bridge__pb2.FrameEvent.FromString,
                _registered_method=True)


class CanBridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIfaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CanBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=proto_dot_can__bridge__pb2.PingReq.FromString,
                    response_serializer=proto_dot_can__bridge__pb2.PingResp.SerializeToString,
            ),
            'ListIfaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIfaces,
                    request_deserializer=proto_dot_can__bridge__pb2.Empty.FromString,
                    response_serializer=proto_dot_can__bridge__pb2.IfacesResp.SerializeToString,
            ),
            'SendFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFrame,
                    request_deserializer=proto_dot_can__bridge__pb2.SendFrameReq.FromString,
                    response_serializer=proto_dot_can__bridge__pb2.SendAck.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=proto_dot_can__bridge__pb2.SubscribeReq.FromString,
                    response_serializer=proto_dot_can__bridge__pb2.FrameEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'canbridge.v1.CanBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('canbridge.v1.CanBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CanBridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canbridge.v1.CanBridge/Ping',
            proto_dot_can__bridge__pb2.PingReq.SerializeToString,
            proto_dot_can__bridge__pb2.PingResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIfaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canbridge.v1.CanBridge/ListIfaces',
            proto_dot_can__bridge__pb2.Empty.SerializeToString,
            proto_dot_can__bridge__pb2.IfacesResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canbridge.v1.CanBridge/SendFrame',
            proto_dot_can__bridge__pb2.SendFrameReq.SerializeToString,
            proto_dot_can__bridge__pb2.SendAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/canbridge.v1.CanBridge/Subscribe',
            proto_dot_can__bridge__pb2.SubscribeReq.SerializeToString,
            proto_dot_can__bridge__pb2.FrameEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
